id: P006894
initial_creation_type: ocr
created_at: 27/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W00KG0547
  title: བྱམས་ཆོས་སྡེ་ལྔ་དང་མངོན་རྟོགས་རྒྱན་གྱི་འགྲེལ་བ།
  author: ''
  volumes:
    ef3f251104a14319b4f91ac91ef845d6:
      image_group_id: I1KG16101
      title: ''
      volume_number: 1
      total_pages: 322
      base_file: v001.txt
